spring.application.name=portfolio-backend

spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT}
spring.data.redis.username=${REDIS_USERNAME}
spring.data.redis.password=${REDIS_PASSWORD}

spring.ai.google.genai.api-key=${GEMINI_API_KEY}
spring.ai.google.genai.embedding.api-key=${GEMINI_API_KEY}
spring.ai.google.genai.chat.options.model=gemini-flash-latest
spring.ai.google.genai.embedding.text.options.model=gemini-embedding-001
spring.ai.google.genai.embedding.text.options.dimensions=2048

spring.ai.vectorstore.qdrant.host=${QDRANT_HOST}
spring.ai.vectorstore.qdrant.port=${QDRANT_PORT}
spring.ai.vectorstore.qdrant.api-key=${QDRANT_API_KEY}
spring.ai.vectorstore.qdrant.use-tls=true
spring.ai.vectorstore.qdrant.collection-name=portfolio
spring.ai.vectorstore.qdrant.initialize-schema=true

spring.ai.ollama.base-url=${OLLAMA_BASE_URL}
spring.ai.ollama.chat.options.model=exaone3.5
spring.ai.ollama.embedding.options.model=exaone3.5

spring.threads.virtual.enabled=true
